# Generated by Django 2.2.15 on 2020-09-13 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200913_1713'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
