# Generated by Django 2.2.15 on 2020-09-13 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
